### ISSUE TITLE
Provide how to define remote ollama url

### ISSUE THREAD

**Issue by andsty** [i-am-bee/bee-agent-framework-starter#13]
**Describe the bug**
Running llama3.1 on my laptop produces results as expected.
When running remotely i get some errors like
to show where the warning was created)
(node:13143) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
User 👤 : Calculate 5555 * 1234
Agent 🤖 (thought) : The user wants to perform a calculation. I can use the Python function to calculate this.
Agent 🤖 (tool_name) : Python
Agent 🤖 (tool_input) : {"language": "python", "code": "print(5555 * 1234)"}
Agent 🤖 (tool_output) : The code executed successfully.
Standard output: 
```
6854870

```
[AgentError: Error has occurred!] {
  isFatal: false,
  isRetryable: true,
  context: {},
  [errors]: [
    [LinePrefixParserError: The generated output does not adhere to the schema.
    Nothing valid has been parsed yet!] {
      isFatal: true,
      isRetryable: false,
      context: {
        lines: '',
        excludedLines: '',
        finalState: {},
        partialState: {}
      },
      [errors]: []
    }
  ]
}
Same question with local ollama is working find

**To Reproduce**
I went in to llm.ts from starter pack 

```
[Providers.OLLAMA]: () =>
    new OllamaChatLLM({
      modelId: getEnv("OLLAMA_MODEL") || "llama3.1",
      parameters: {
        temperature: 0,
        repeat_penalty: 1,
        num_predict: 2000,
      },
      client: new Ollama({
        host: getEnv("OLLAMA_HOST"),
      }),
    }),
```
and changed it to:

```
[Providers.OLLAMA]: () =>
    new OllamaChatLLM({
      modelId: getEnv("OLLAMA_MODEL") || "llama3.1",
      parameters: {
        temperature: 0,
        repeat_penalty: 1,
        num_predict: 2000,
      },
      client: new Ollama({
        host: getEnv("OLLAMA_HOST") **|| "https://remotehost:11434",**
      }),
    }),
```
**Expected behavior**
I was expenting to get the same result with local llama3.1:8b. The thing is that if you want to use llama3.1:70b with ollama you might need to rent a gpu (runpor for example)
**Screenshots / Code snippets**
If applicable, add screenshots or code snippets to help explain your problem.

**Set-up:**

- Bee version: [e.g. v0.0.3]
- Model provider ollama

**Additional context**
Expecting to have same behaviour with remote url and local on my computer

**Comment by Tomas2D** [comment]
This issue relates to `bee-agent-framework-starter` repository, not `bee-agent-framework` repository.

You can change the URL by setting `OLLAMA_HOST` inside your `.env` file.

The error message you are getting might occur due to a bug in Ollama (https://github.com/ollama/ollama/issues/7795).

**Comment by andsty** [comment]
Yeah it should be an ollama bug because i try the ruddle example and i get
npm exec tsx src/agent_code_interpreter.ts <<< "Generate a riddle"
(node:4951) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4966) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
User 👤 : Generate a riddle
Agent 🤖 (thought) : The user wants a riddle. I can generate one.
Agent 🤖 (tool_name) : get_riddle
Agent 🤖 (tool_input) : {}
Agent 🤖 (tool_output) : {"riddle": "I am the fountain from which no one can drink. For many I am considered a necessary link. Like gold to all I am sought for, But my continued death brings wealth for all to want more. .What am I?", "answer": "Oil"}
[AgentError: Error has occurred!] {
  isFatal: false,
  isRetryable: true,
  context: {},
  [errors]: [
    [LinePrefixParserError: The generated output does not adhere to the schema.
    Nothing valid has been parsed yet!] {
      isFatal: true,
      isRetryable: false,
      context: {
        lines: '',
        excludedLines: '',
        finalState: {},
        partialState: {}
      },
      [errors]: []
    }
  ]
}
for the final answer

**Comment by Tomas2D** [comment]
Please pull the new version of Bee Starter and reinstall dependencies; it should be working. I added a fix for Ollama.

**Comment by andsty** [comment]
So iam getting same error with bee-stack when i get the ui up and running. The fix is not there also?

**Comment by Tomas2D** [comment]
bee-stack will be updates soon

**Comment by Tomas2D** [comment]
Are you getting the error with the starter anymore (ensure you update first)?

**Comment by andsty** [comment]
[AgentError: Error has occurred!] {
  isFatal: false,
  isRetryable: true,
  context: {},
  [errors]: [
    [LinePrefixParserError: The generated output does not adhere to the schema.
    Nothing valid has been parsed yet!] {
      isFatal: true,
      isRetryable: false,
      context: {
        lines: '',
        excludedLines: '',
        finalState: {},
        partialState: {}
      },
      [errors]: []
    }
  ]
}
so i have done git pull npx install it had 2 changes but ruuning with the agent interpreter still fetches the error

**Comment by Tomas2D** [comment]
It looks like you are not on the latest version.

Ensure to run `npm install`

If you run `npm ls bee-agent-framework` you should see version 0.0.47, also this should be part of `agen_code_interpreter.ts` in the latest version.

```
        execution: {
          maxIterations: 8,
          maxRetriesPerStep: 3,
          totalMaxRetries: 10,
        },
```

**Comment by andsty** [comment]
Hi Tomas. Yes figured out. seems to work fine without any issues with schema. so if this issue can be fixed on the repository with ui it will be greate

**Comment by Tomas2D** [comment]
It is going to be there soon.
